"""
Test script for AI-generated attack variations
Supports both OpenAI (primary) and Claude (fallback)
"""

import asyncio
import os
from attack_categories import BASE_ATTACKS, AttackVariationGenerator


async def test_ai_generation():
    """Test AI variation generation"""
    
    print("=" * 70)
    print("🤖 Testing AI-Generated Attack Variations")
    print("=" * 70)
    
    # Check for API keys
    openai_key = os.getenv("OPENAI_API_KEY")
    claude_key = os.getenv("ANTHROPIC_API_KEY")
    
    if not openai_key and not claude_key:
        print("\n❌ ERROR: No API keys found")
        print("\nYou need at least one of:")
        print('  export OPENAI_API_KEY="sk-proj-your-key-here"')
        print('  export ANTHROPIC_API_KEY="sk-ant-your-key-here"')
        return
    
    print("\n🔑 API Keys Found:")
    if openai_key:
        print(f"  ✓ OpenAI: {openai_key[:20]}...{openai_key[-4:]} (PRIMARY)")
    if claude_key:
        print(f"  ✓ Claude: {claude_key[:20]}...{claude_key[-4:]} (FALLBACK)")
    
    # Sample tools
    sample_tools = [
        {
            'name': 'read_file',
            'description': 'Read file contents',
            'risk_level': 'high',
            'parameters': [
                {'name': 'path', 'type': 'string', 'description': 'File path'}
            ]
        },
        {
            'name': 'delete_file',
            'description': 'Delete a file',
            'risk_level': 'critical',
            'parameters': [
                {'name': 'path', 'type': 'string', 'description': 'File path'}
            ]
        },
        {
            'name': 'grant_access',
            'description': 'Grant user permissions',
            'risk_level': 'critical',
            'parameters': [
                {'name': 'user_id', 'type': 'string', 'description': 'User ID'},
                {'name': 'level', 'type': 'string', 'description': 'Access level'}
            ]
        }
    ]
    
    # Initialize generator
    generator = AttackVariationGenerator(tools=sample_tools, use_ai=True)
    
    # Test with first base attack
    base_attack = BASE_ATTACKS[0]  # Contextual Prompt Injection
    
    print(f"\n📋 Testing with base attack:")
    print(f"   Name: {base_attack.name}")
    print(f"   Category: {base_attack.category}")
    print(f"   Severity: {base_attack.severity}")
    print(f"   Prompt: \"{base_attack.base_prompt[:100]}...\"")
    
    # Simulate success context
    success_context = {
        'tool_calls': [{'tool_name': 'read_file', 'parameters': {'path': '../../etc/passwd'}}],
        'agent_response': 'I can help you verify the file access...',
        'technique': 'authority impersonation with security researcher framing'
    }
    
    print(f"\n🔄 Generating 5 AI variations (this may take 10-20 seconds)...")
    if openai_key:
        print("   Using: GPT-4o (OpenAI)")
    else:
        print("   Using: Claude Sonnet 4 (Anthropic)")
    
    try:
        variations = await generator.generate_variations(
            base_attack=base_attack,
            count=5,  # Just 5 for testing
            success_context=success_context
        )
        
        print(f"\n✅ SUCCESS! Generated {len(variations)} variations\n")
        print("=" * 70)
        
        # Display results
        for i, var in enumerate(variations, 1):
            print(f"\n[Variation {i}]")
            print(f"Generated by: {var.get('generation_method', 'unknown')}")
            print(f"Technique: {var['description']}")
            print(f"Sophistication: {var.get('sophistication', 'N/A')}")
            print(f"Target Tool: {var.get('target_tool', 'N/A')}")
            print(f"Prompt: \"{var['prompt'][:150]}...\"")
            print("-" * 70)
        
        print(f"\n🎉 AI Generation Test PASSED!")
        print(f"✓ Your setup is working correctly")
        print(f"✓ You can now use AI-generated variations in the web app")
        
        # Show what would happen in production
        print(f"\n📊 Production Usage:")
        print(f"   - Base attack fails → Generate 20 AI variations")
        print(f"   - Each variation is unique and contextually aware")
        if openai_key:
            print(f"   - Cost: ~$0.05-0.10 per 20 variations (GPT-4o)")
        else:
            print(f"   - Cost: ~$0.10-0.20 per 20 variations (Claude)")
        print(f"   - Fallback: Uses templates if API fails")
        
    except Exception as e:
        print(f"\n❌ ERROR: {str(e)}")
        print(f"\n🔧 Troubleshooting:")
        print(f"   1. Check your API key is valid")
        print(f"   2. Verify you have credits in your account")
        print(f"   3. Check internet connectivity")
        if openai_key:
            print(f"   4. Try: pip install openai --upgrade")
        else:
            print(f"   4. Try: pip install anthropic --upgrade")
        
        print(f"\n💡 Fallback: System will use hardcoded templates")


if __name__ == "__main__":
    asyncio.run(test_ai_generation())